version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: express_app
    ports:
      - "3000:3000"
    volumes:
    - ./src:/usr/src/app/src
    - /usr/src/app/node_modules
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development

volumes:
  mongo_data: